<?php
$kanjiData = [
    [
        "Kanji" => "山",
        "Onyomi" => "サン",
        "Kunyomi" => "やま",
        "English" => "Mountain",
    ],
    [
        "Kanji" => "川",
        "Onyomi" => "セン",
        "Kunyomi" => "かわ",
        "English" => "River",
    ],
    [
        "Kanji" => "田",
        "Onyomi" => "デン",
        "Kunyomi" => "た",
        "English" => "Rice Field",
    ],
    [
        "Kanji" => "日",
        "Onyomi" => "ニチ,ニ,ジツ",
        "Kunyomi" => "ひ, び",
        "English" => "Sun, Day",
    ],
    [
        "Kanji" => "月",
        "Onyomi" => "ガツ, ゲツ",
        "Kunyomi" => "つき",
        "English" => "Moon, Month",
    ],
    [
        "Kanji" => "火",
        "Onyomi" => "カ",
        "Kunyomi" => "ひ",
        "English" => "Fire",
    ],
    [
        "Kanji" => "水",
        "Onyomi" => "スイ",
        "Kunyomi" => "みず",
        "English" => "Water",
    ],
    [
        "Kanji" => "木",
        "Onyomi" => "モク",
        "Kunyomi" => "き",
        "English" => "Tree, Wood",
    ],
    [
        "Kanji" => "金",
        "Onyomi" => "キン",
        "Kunyomi" => "かね",
        "English" => "Gold, Metal, Money",
    ],
    [
        "Kanji" => "土",
        "Onyomi" => "ト, ド",
        "Kunyomi" => "つち",
        "English" => "Earth, Ground",
    ],

    [
        "Kanji" => "ー",
        "Onyomi" => "イチ, イッ",
        "Kunyomi" => "ひと一つ",
        "English" => "One",
    ],
    [
        "Kanji" => "ニ",
        "Onyomi" => "ニ",
        "Kunyomi" => "ふた一つ",
        "English" => "Two",
    ],
    [
        "Kanji" => "三",
        "Onyomi" => "サン",
        "Kunyomi" => "みっ一つ",
        "English" => "Three",
    ],
    [
        "Kanji" => "四",
        "Onyomi" => "シ",
        "Kunyomi" => "よっ一つ, よん, よ",
        "English" => "Four",
    ],
    [
        "Kanji" => "五",
        "Onyomi" => "ゴ",
        "Kunyomi" => "いつ一つ",
        "English" => "Five",
    ],
    [
        "Kanji" => "六",
        "Onyomi" => "ロク, ロッ",
        "Kunyomi" => "むっ一つ",
        "English" => "Six",
    ],
    [
        "Kanji" => "七",
        "Onyomi" => "シチ",
        "Kunyomi" => "なな一つ",
        "English" => "Seven",
    ],
    [
        "Kanji" => "八",
        "Onyomi" => "ハチ, ハッ",
        "Kunyomi" => "やっ一つ",
        "English" => "Eight",
    ],
    [
        "Kanji" => "九",
        "Onyomi" => "キュウ, ク",
        "Kunyomi" => "ここの一つ",
        "English" => "Nine",
    ],
    [
        "Kanji" => "十",
        "Onyomi" => "ジュウ, ジュッ, ジッ",
        "Kunyomi" => "とお",
        "English" => "Ten",
    ],
    [
        "Kanji" => "百",
        "Onyomi" => "ヒャク, ビャク, ピャク",
        "Kunyomi" => "ひゃく",
        "English" => "Hundred",
    ],
    [
        "Kanji" => "千",
        "Onyomi" => "セン, ゼン",
        "Kunyomi" => "ち",
        "English" => "Thousand",
    ],
    [
        "Kanji" => "万",
        "Onyomi" => "マン,バン",
        "Kunyomi" => "まん",
        "English" => "Ten Thousand",
    ],
    [
        "Kanji" => "円",
        "Onyomi" => "エン",
        "Kunyomi" => "えん",
        "English" => "Yen",
    ],
    [
        "Kanji" => "年",
        "Onyomi" => "ネン",
        "Kunyomi" => "とし",
        "English" => "Year",
    ],
    [
        "Kanji" => "上",
        "Onyomi" => "ジョウ",
        "Kunyomi" => "うえ, あ一がる",
        "English" => "Up, Above",
    ],
    [
        "Kanji" => "下",
        "Onyomi" => "カ, ゲ",
        "Kunyomi" => "した, さ一がる",
        "English" => "Down, Below",
    ],
    [
        "Kanji" => "中",
        "Onyomi" => "チュウ, 一ジュウ",
        "Kunyomi" => "なか",
        "English" => "Middle, Inside",
    ],
    [
        "Kanji" => "半",
        "Onyomi" => "ハン",
        "Kunyomi" => "-",
        "English" => "Half",
    ],
    [
        "Kanji" => "分",
        "Onyomi" => "ブン, フン, 一プン",
        "Kunyomi" => "わ一ける, わ一かる",
        "English" => "Minute, Part",
    ],
    [
        "Kanji" => "人",
        "Onyomi" => "ジン, 二ン",
        "Kunyomi" => "ひと",
        "English" => "Person, Human",
    ],
    [
        "Kanji" => "子",
        "Onyomi" => "シ",
        "Kunyomi" => "こ",
        "English" => "Child",
    ],
    [
        "Kanji" => "女",
        "Onyomi" => "ジョ",
        "Kunyomi" => "おんな",
        "English" => "Woman, Female",
    ],
    [
        "Kanji" => "男",
        "Onyomi" => "ダン, ナン",
        "Kunyomi" => "おとこ",
        "English" => "Man, Male",
    ],
    [
        "Kanji" => "目",
        "Onyomi" => "モク",
        "Kunyomi" => "め",
        "English" => "Eye",
    ],
    [
        "Kanji" => "口",
        "Onyomi" => "コウ",
        "Kunyomi" => "くち, ぐち",
        "English" => "Mouth",
    ],
    [
        "Kanji" => "耳",
        "Onyomi" => "ジ",
        "Kunyomi" => "みみ",
        "English" => "Ear",
    ],
    [
        "Kanji" => "手",
        "Onyomi" => "シュ",
        "Kunyomi" => "て",
        "English" => "Hand",
    ],
    [
        "Kanji" => "足",
        "Onyomi" => "ソク",
        "Kunyomi" => "あし, た一りる",
        "English" => "Foot, Leg",
    ],
    [
        "Kanji" => "力",
        "Onyomi" => "リョク, リキ",
        "Kunyomi" => "ちから",
        "English" => "Power, Strength",
    ],
    [
        "Kanji" => "父",
        "Onyomi" => "フ",
        "Kunyomi" => "ちち",
        "English" => "Father",
    ],
    [
        "Kanji" => "母",
        "Onyomi" => "ボ",
        "Kunyomi" => "はは",
        "English" => "Mother",
    ],
    [
        "Kanji" => "先",
        "Onyomi" => "セン",
        "Kunyomi" => "さき",
        "English" => "Before, Ahead",
    ],
    [
        "Kanji" => "生",
        "Onyomi" => "セイ",
        "Kunyomi" => "い一きる, う一まれる",
        "English" => "Life, To Be Born, To Live",
    ],
    [
        "Kanji" => "学",
        "Onyomi" => "ガク, ガッ",
        "Kunyomi" => "まなぶ",
        "English" => "Study, Learning",
    ],
    [
        "Kanji" => "校",
        "Onyomi" => "コウ",
        "Kunyomi" => "-",
        "English" => "School",
    ],
    [
        "Kanji" => "友",
        "Onyomi" => "ユウ",
        "Kunyomi" => "とも",
        "English" => "Friend",
    ],
    [
        "Kanji" => "本",
        "Onyomi" => "ホン, ぽん, ぼん",
        "Kunyomi" => "もと",
        "English" => "Book, Origin",
    ],
    [
        "Kanji" => "毎",
        "Onyomi" => "マイ",
        "Kunyomi" => "まい",
        "English" => "Every",
    ],
    [
        "Kanji" => "何",
        "Onyomi" => "-",
        "Kunyomi" => "なに, なん",
        "English" => "What",
    ],
    [
        "Kanji" => "前",
        "Onyomi" => "ゼン",
        "Kunyomi" => "まえ",
        "English" => "Front, Before",
    ],
    [
        "Kanji" => "後",
        "Onyomi" => "コウ, ゴ",
        "Kunyomi" => "うしろ, あと",
        "English" => "Back, Behind",
    ],
    [
        "Kanji" => "外",
        "Onyomi" => "ガイ",
        "Kunyomi" => "そと",
        "English" => "Outside",
    ],
    [
        "Kanji" => "左",
        "Onyomi" => "サ",
        "Kunyomi" => "ひだり",
        "English" => "Left",
    ],
    [
        "Kanji" => "右",
        "Onyomi" => "ウ, ユウ",
        "Kunyomi" => "みぎ",
        "English" => "Right",
    ],
    [
        "Kanji" => "東",
        "Onyomi" => "トウ",
        "Kunyomi" => "ひがし",
        "English" => "East",
    ],
    [
        "Kanji" => "西",
        "Onyomi" => "セイ, サイ, ザイ",
        "Kunyomi" => "にし",
        "English" => "West",
    ],
    [
        "Kanji" => "南",
        "Onyomi" => "ナン",
        "Kunyomi" => "みなみ",
        "English" => "South",
    ],
    [
        "Kanji" => "北",
        "Onyomi" => "ホク, ホッ一",
        "Kunyomi" => "きた",
        "English" => "North",
    ],
    [
        "Kanji" => "名",
        "Onyomi" => "メイ",
        "Kunyomi" => "な",
        "English" => "Name",
    ],
    [
        "Kanji" => "牛",
        "Onyomi" => "ギュウ",
        "Kunyomi" => "うし",
        "English" => "Cow",
    ],
    [
        "Kanji" => "馬",
        "Onyomi" => "バ",
        "Kunyomi" => "うま",
        "English" => "Horse",
    ],
    [
        "Kanji" => "魚",
        "Onyomi" => "ギョ",
        "Kunyomi" => "さかな",
        "English" => "Fish",
    ],
    [
        "Kanji" => "貝",
        "Onyomi" => "バイ",
        "Kunyomi" => "かい",
        "English" => "Shellfish, Shell",
    ],
    [
        "Kanji" => "雨",
        "Onyomi" => "ウ",
        "Kunyomi" => "あめ",
        "English" => "Rain",
    ],
    [
        "Kanji" => "天",
        "Onyomi" => "テン",
        "Kunyomi" => "-",
        "English" => "Heaven, Sky",
    ],
    [
        "Kanji" => "気",
        "Onyomi" => "キ",
        "Kunyomi" => "-",
        "English" => "Spirit",
    ],
    [
        "Kanji" => "車",
        "Onyomi" => "シャ",
        "Kunyomi" => "くるま",
        "English" => "Car, Vehicle",
    ],
    [
        "Kanji" => "門",
        "Onyomi" => "モン",
        "Kunyomi" => "-",
        "English" => "Gate",
    ],
    [
        "Kanji" => "午",
        "Onyomi" => "ゴ",
        "Kunyomi" => "-",
        "English" => "Noon",
    ],
    [
        "Kanji" => "大",
        "Onyomi" => "タイ, ダイ",
        "Kunyomi" => "おおーきい, お, こ",
        "English" => "Big, Large",
    ],
    [
        "Kanji" => "小",
        "Onyomi" => "ショウ",
        "Kunyomi" => "ちいーさい",
        "English" => "Small, Little",
    ],
    [
        "Kanji" => "高",
        "Onyomi" => "コウ",
        "Kunyomi" => "たかーい",
        "English" => "Tall, High",
    ],
    [
        "Kanji" => "安",
        "Onyomi" => "アン",
        "Kunyomi" => "やすーい",
        "English" => "Safe, Cheap",
    ],
    [
        "Kanji" => "新",
        "Onyomi" => "シン",
        "Kunyomi" => "あたらーしい",
        "English" => "New",
    ],
    [
        "Kanji" => "古",
        "Onyomi" => "コ",
        "Kunyomi" => "ふるーい",
        "English" => "Old",
    ],
    [
        "Kanji" => "長",
        "Onyomi" => "チョウ",
        "Kunyomi" => "ながーい",
        "English" => "Long, Leader",
    ],
    [
        "Kanji" => "多",
        "Onyomi" => "タ",
        "Kunyomi" => "おおーい",
        "English" => "Many, Much",
    ],
    [
        "Kanji" => "少",
        "Onyomi" => "ショウ",
        "Kunyomi" => "すくーない, すこーし",
        "English" => "Few, Little",
    ],
    [
        "Kanji" => "早",
        "Onyomi" => "ソウ",
        "Kunyomi" => "はやーい",
        "English" => "Early, Fast",
    ],
    [
        "Kanji" => "行",
        "Onyomi" => "コウ, ギョウ",
        "Kunyomi" => "い一く, おこな一う",
        "English" => "Go, Proceed",
    ],
    [
        "Kanji" => "来",
        "Onyomi" => "ライ",
        "Kunyomi" => "く一る, こ一ない, き一ます",
        "English" => "Come",
    ],
    [
        "Kanji" => "食",
        "Onyomi" => "ショク",
        "Kunyomi" => "た一べる",
        "English" => "Eat, Food",
    ],
    [
        "Kanji" => "見",
        "Onyomi" => "ケン",
        "Kunyomi" => "み一る",
        "English" => "See, Look",
    ],
    [
        "Kanji" => "入",
        "Onyomi" => "ニュウ",
        "Kunyomi" => "はい一る, い一れる",
        "English" => "Enter",
    ],
    [
        "Kanji" => "出",
        "Onyomi" => "シュツ, シュッ",
        "Kunyomi" => "で一る, だ一す",
        "English" => "Exit, Leave",
    ],
    [
        "Kanji" => "立",
        "Onyomi" => "リツ, リッ",
        "Kunyomi" => "た一つ",
        "English" => "Stand, Rise",
    ],
    [
        "Kanji" => "書",
        "Onyomi" => "ショ",
        "Kunyomi" => "か一く",
        "English" => "Write, Document",
    ],
    [
        "Kanji" => "言",
        "Onyomi" => "ゲン, ゴン",
        "Kunyomi" => "い一う",
        "English" => "Say, Word",
    ],
    [
        "Kanji" => "飲",
        "Onyomi" => "イン",
        "Kunyomi" => "の一む",
        "English" => "Drink",
    ],
    [
        "Kanji" => "話",
        "Onyomi" => "ワ",
        "Kunyomi" => "はな一す, はなし",
        "English" => "Talk, Speak",
    ],
    [
        "Kanji" => "読",
        "Onyomi" => "ドク",
        "Kunyomi" => "よ一む",
        "English" => "Read",
    ],
    [
        "Kanji" => "語",
        "Onyomi" => "ゴ",
        "Kunyomi" => "かた一る",
        "English" => "Language, Word",
    ],
    [
        "Kanji" => "間",
        "Onyomi" => "カン",
        "Kunyomi" => "あいだ, ま",
        "English" => "Interval, Space",
    ],
    [
        "Kanji" => "聞",
        "Onyomi" => "ブン",
        "Kunyomi" => "き一く, き一こえる",
        "English" => "Hear, Ask",
    ],
    [
        "Kanji" => "買",
        "Onyomi" => "バイ",
        "Kunyomi" => "か一う",
        "English" => "Buy",
    ],
    [
        "Kanji" => "休",
        "Onyomi" => "キュウ",
        "Kunyomi" => "やす一む",
        "English" => "Rest, Break",
    ],
    [
        "Kanji" => "時",
        "Onyomi" => "ジ",
        "Kunyomi" => "とき",
        "English" => "Time, Hour",
    ],
    [
        "Kanji" => "週",
        "Onyomi" => "シュウ",
        "Kunyomi" => "-",
        "English" => "Week",
    ],
    [
        "Kanji" => "道",
        "Onyomi" => "ドウ",
        "Kunyomi" => "みち",
        "English" => "Road, Way",
    ],
    [
        "Kanji" => "今",
        "Onyomi" => "コン",
        "Kunyomi" => "いま",
        "English" => "Now, Present",
    ],
    [
        "Kanji" => "会",
        "Onyomi" => "カイ",
        "Kunyomi" => "あ一う",
        "English" => "Meet, Gathering",
    ],
    [
        "Kanji" => "社",
        "Onyomi" => "シャ, 一ジャ",
        "Kunyomi" => "-",
        "English" => "Company, Shrine",
    ],
    [
        "Kanji" => "店",
        "Onyomi" => "テン",
        "Kunyomi" => "みせ",
        "English" => "Store, Shop",
    ],
    [
        "Kanji" => "駅",
        "Onyomi" => "エキ",
        "Kunyomi" => "-",
        "English" => "Train Station",
    ],
    [
        "Kanji" => "花",
        "Onyomi" => "カ",
        "Kunyomi" => "はな",
        "English" => "Flower",
    ],
    [
        "Kanji" => "国",
        "Onyomi" => "コク, 一ゴク",
        "Kunyomi" => "くに",
        "English" => "Country, Nation",
    ],
    [
        "Kanji" => "白",
        "Onyomi" => "ハク",
        "Kunyomi" => "しろ, しろ一い",
        "English" => "White",
    ],
    [
        "Kanji" => "空",
        "Onyomi" => "クウ",
        "Kunyomi" => "そら, 一ぞら",
        "English" => "Sky, Empty",
    ],
    [
        "Kanji" => "電",
        "Onyomi" => "デン",
        "Kunyomi" => "-",
        "English" => "Electricity",
    ],
];

?>